walker_server/config/routes.rb
Rails.application.routes.draw do

  resources :items

  resources :qrevents

  resources :items_users

  resources :gpsquests

  resources :qrlogs

  resources :steplogs

  resources :gpslogs

  resources :users

	get '/walker/sensor/gpsquests/get_questlist' => 'sensor_api#getGpsQuestList'
	post '/walker/sensor/steps/post_step' => 'sensor_api#postStep'
	post '/walker/sensor/gpsquests/post_location' => 'sensor_api#postLocation'
	post '/walker/sensor/qrcodes/post_qrcode' => 'sensor_api#postQRcode'

	get '/walker/game/items/get_items_entity' => 'game_api#getItemEntity'
	get '/walker/game/steps/get_step' => 'game_api#getStep'
	get '/walker/game/steps/post_step' => 'game_api#postStep'
	get '/walker/game/items/post_items' => 'game_api#postItems'

end

walker_server/app/models/gpslog.rb
class Gpslog < ActiveRecord::Base
end

walker_server/app/models/gpsquest.rb
class Gpsquest < ActiveRecord::Base
end

walker_server/app/models/item.rb
class Item < ActiveRecord::Base
end

walker_server/app/models/items_user.rb
class ItemsUser < ActiveRecord::Base
end

walker_server/app/models/items_users.rb
class ItemsUsers < ActiveRecord::Base
end

walker_server/app/models/lotrate.rb
class Lotrate < ActiveRecord::Base
end

walker_server/app/models/qrevent.rb
class Qrevent < ActiveRecord::Base
end

walker_server/app/models/qrlog.rb
class Qrlog < ActiveRecord::Base
end

walker_server/app/models/step.rb
class Step < ActiveRecord::Base
end

walker_server/app/models/step_user.rb
class StepUser < ActiveRecord::Base
end

walker_server/app/models/steplog.rb
class Steplog < ActiveRecord::Base
end

walker_server/app/models/user.rb
class User < ActiveRecord::Base
end

walker_server/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :effective_term, :effective_value, :description)
    end
end

walker_server/app/helpers/api_helper.rb
module ApiHelper
end

walker_server/app/helpers/game_api_helper.rb
module GameApiHelper
end

walker_server/app/helpers/gpslogs_helper.rb
module GpslogsHelper
end

walker_server/app/helpers/gpsquests_helper.rb
module GpsquestsHelper
end

walker_server/app/helpers/items_helper.rb
module ItemsHelper
end

walker_server/app/helpers/qrevents_helper.rb
module QreventsHelper
end

walker_server/app/helpers/qrlogs_helper.rb
module QrlogsHelper
end

walker_server/app/helpers/sensor_api_helper.rb
module SensorApiHelper
end

walker_server/app/helpers/steplogs_helper.rb
module SteplogsHelper
end

walker_server/app/helpers/users_helper.rb
module UsersHelper
end

walker_server/app/views/item/_form.html.haml
= form_for @item, html: { class: "form form-horizontal item" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@item[:name])
  .form-group
    = f.label :effective_term, class: 'control-label'
    .controls
      = f.text_field :effective_term, class: 'form-control', required: true
    = error_span(@item[:effective_term])
  .form-group
    = f.label :effective_value, class: 'control-label'
    .controls
      = f.text_field :effective_value, class: 'form-control', required: true
    = error_span(@item[:effective_value])
  .form-group
    = f.label :description, class: 'control-label'
    .controls
      = f.text_field :description, class: 'form-control', required: true
    = error_span(@item[:description])
  .form-group
    = f.label :description, class: 'control-label'
    .controls
      = f.text_field :description, class: 'form-control', required: true
    = error_span(@item[:description])

  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), items_path, :class => 'btn btn-default'

walker_server/app/views/item/edit.html.haml
- model_class = Item
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

walker_server/app/views/item/index.html.haml
- model_class = Item
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:classification)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @items.each do |item|
      %tr
        %td= link_to item.id, item_path(item)
        %td= item.name
        %td= item.classification
        %td= item.description
        %td=l item.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_item_path(item), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), item_path(item), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_item_path, :class => 'btn btn-primary'

walker_server/app/views/item/new.html.haml
- model_class = Item
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

walker_server/app/views/item/show.html.haml
- model_class = Item
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @item.name
%p
  %strong= model_class.human_attribute_name(:classification) + ':'
  %br
  = @item.classification
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @item.description


= link_to t('.back', :default => t("helpers.links.back")), items_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_item_path(@item), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), item_path(@item), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

walker_server/app/views/items/_form.html.haml
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :effective_term
    = f.text_field :effective_term
  .field
    = f.label :effective_value
    = f.text_field :effective_value
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

walker_server/app/views/items/edit.html.haml
%h1 Editing item

= render 'form'

= link_to 'Show', @item
\|
= link_to 'Back', items_path

walker_server/app/views/items/index.html.haml
%h1 Listing items

%table{:style => "border: 1px; width 100%"}
  %thead
    %tr
      %th Name
      %th Effective term
      %th Effective value
      %th Description
      %th
      %th
      %th
      
  %tbody
    - @items.each do |item|
      %tr
        %td= item.name
        %td= item.effective_term
        %td= item.effective_value
        %td= item.description
        %td= link_to 'Show', item
        %td= link_to 'Edit', edit_item_path(item)
        %td= link_to 'Destroy', item, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Item', new_item_path

walker_server/app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

walker_server/app/views/items/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @item.name
%p
  %b Effective term:
  = @item.effective_term
%p
  %b Effective value:
  = @item.effective_value
%p
  %b Description:
  = @item.description

= link_to 'Edit', edit_item_path(@item)
\|
= link_to 'Back', items_path