walker_server/config/routes.rb
Rails.application.routes.draw do

  resources :items

  resources :qrevents

  resources :items_users

  resources :gpsquests

  resources :qrlogs

  resources :steplogs

  resources :gpslogs

  resources :users

	get '/walker/sensor/gpsquests/get_questlist' => 'sensor_api#getGpsQuestList'
	post '/walker/sensor/steps/post_step' => 'sensor_api#postStep'
	post '/walker/sensor/gpsquests/post_location' => 'sensor_api#postLocation'
	post '/walker/sensor/qrcodes/post_qrcode' => 'sensor_api#postQRcode'

	get '/walker/game/items/get_items_entity' => 'game_api#getItemEntity'
	get '/walker/game/steps/get_step' => 'game_api#getStep'
	get '/walker/game/steps/post_step' => 'game_api#postStep'
	get '/walker/game/items/post_items' => 'game_api#postItems'

end

walker_server/app/models/gpslog.rb
class Gpslog < ActiveRecord::Base
end

walker_server/app/models/gpsquest.rb
class Gpsquest < ActiveRecord::Base
end

walker_server/app/models/item.rb
class Item < ActiveRecord::Base
end

walker_server/app/models/items_user.rb
class ItemsUser < ActiveRecord::Base
end

walker_server/app/models/items_users.rb
class ItemsUsers < ActiveRecord::Base
end

walker_server/app/models/lotrate.rb
class Lotrate < ActiveRecord::Base
end

walker_server/app/models/qrevent.rb
class Qrevent < ActiveRecord::Base
end

walker_server/app/models/qrlog.rb
class Qrlog < ActiveRecord::Base
end

walker_server/app/models/step.rb
class Step < ActiveRecord::Base
end

walker_server/app/models/step_user.rb
class StepUser < ActiveRecord::Base
end

walker_server/app/models/steplog.rb
class Steplog < ActiveRecord::Base
end

walker_server/app/models/user.rb
class User < ActiveRecord::Base
end

walker_server/app/controllers/qrlogs_controller.rb
class QrlogsController < ApplicationController
  before_action :set_qrlog, only: [:show, :edit, :update, :destroy]

  # GET /qrlogs
  # GET /qrlogs.json
  def index
    @qrlogs = Qrlog.all
  end

  # GET /qrlogs/1
  # GET /qrlogs/1.json
  def show
  end

  # GET /qrlogs/new
  def new
    @qrlog = Qrlog.new
  end

  # GET /qrlogs/1/edit
  def edit
  end

  # POST /qrlogs
  # POST /qrlogs.json
  def create
    @qrlog = Qrlog.new(qrlog_params)

    respond_to do |format|
      if @qrlog.save
        format.html { redirect_to @qrlog, notice: 'Qrlog was successfully created.' }
        format.json { render :show, status: :created, location: @qrlog }
      else
        format.html { render :new }
        format.json { render json: @qrlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qrlogs/1
  # PATCH/PUT /qrlogs/1.json
  def update
    respond_to do |format|
      if @qrlog.update(qrlog_params)
        format.html { redirect_to @qrlog, notice: 'Qrlog was successfully updated.' }
        format.json { render :show, status: :ok, location: @qrlog }
      else
        format.html { render :edit }
        format.json { render json: @qrlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qrlogs/1
  # DELETE /qrlogs/1.json
  def destroy
    @qrlog.destroy
    respond_to do |format|
      format.html { redirect_to qrlogs_url, notice: 'Qrlog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qrlog
      @qrlog = Qrlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qrlog_params
      params.require(:qrlog).permit(:userhash, :code)
    end
end

walker_server/app/helpers/api_helper.rb
module ApiHelper
end

walker_server/app/helpers/game_api_helper.rb
module GameApiHelper
end

walker_server/app/helpers/gpslogs_helper.rb
module GpslogsHelper
end

walker_server/app/helpers/gpsquests_helper.rb
module GpsquestsHelper
end

walker_server/app/helpers/items_helper.rb
module ItemsHelper
end

walker_server/app/helpers/qrevents_helper.rb
module QreventsHelper
end

walker_server/app/helpers/qrlogs_helper.rb
module QrlogsHelper
end

walker_server/app/helpers/sensor_api_helper.rb
module SensorApiHelper
end

walker_server/app/helpers/steplogs_helper.rb
module SteplogsHelper
end

walker_server/app/helpers/users_helper.rb
module UsersHelper
end

walker_server/app/views/qrlogs/_form.html.haml
= form_for @qrlog do |f|
  - if @qrlog.errors.any?
    #error_explanation
      %h2= "#{pluralize(@qrlog.errors.count, "error")} prohibited this qrlog from being saved:"
      %ul
        - @qrlog.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :userhash
    = f.text_field :userhash
  .field
    = f.label :code
    = f.text_field :code
  .actions
    = f.submit 'Save'

walker_server/app/views/qrlogs/edit.html.haml
%h1 Editing qrlog

= render 'form'

= link_to 'Show', @qrlog
\|
= link_to 'Back', qrlogs_path

walker_server/app/views/qrlogs/index.html.haml
%h1 Listing qrlogs

%table
  %thead
    %tr
      %th Userhash
      %th Code
      %th
      %th
      %th
      
  %tbody
    - @qrlogs.each do |qrlog|
      %tr
        %td= qrlog.userhash
        %td= qrlog.code
        %td= link_to 'Show', qrlog
        %td= link_to 'Edit', edit_qrlog_path(qrlog)
        %td= link_to 'Destroy', qrlog, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Qrlog', new_qrlog_path

walker_server/app/views/qrlogs/new.html.haml
%h1 New qrlog

= render 'form'

= link_to 'Back', qrlogs_path

walker_server/app/views/qrlogs/show.html.haml
%p#notice= notice

%p
  %b Userhash:
  = @qrlog.userhash
%p
  %b Code:
  = @qrlog.code

= link_to 'Edit', edit_qrlog_path(@qrlog)
\|
= link_to 'Back', qrlogs_path