walker_server/config/routes.rb
Rails.application.routes.draw do

  resources :items

  resources :qrevents

  resources :items_users

  resources :gpsquests

  resources :qrlogs

  resources :steplogs

  resources :gpslogs

  resources :users

	get '/walker/sensor/gpsquests/get_questlist' => 'sensor_api#getGpsQuestList'
	post '/walker/sensor/steps/post_step' => 'sensor_api#postStep'
	post '/walker/sensor/gpsquests/post_location' => 'sensor_api#postLocation'
	post '/walker/sensor/qrcodes/post_qrcode' => 'sensor_api#postQRcode'

	get '/walker/game/items/get_items_entity' => 'game_api#getItemEntity'
	get '/walker/game/steps/get_step' => 'game_api#getStep'
	get '/walker/game/steps/post_step' => 'game_api#postStep'
	get '/walker/game/items/post_items' => 'game_api#postItems'

end

walker_server/app/models/gpslog.rb
class Gpslog < ActiveRecord::Base
end

walker_server/app/models/gpsquest.rb
class Gpsquest < ActiveRecord::Base
end

walker_server/app/models/item.rb
class Item < ActiveRecord::Base
end

walker_server/app/models/items_user.rb
class ItemsUser < ActiveRecord::Base
end

walker_server/app/models/items_users.rb
class ItemsUsers < ActiveRecord::Base
end

walker_server/app/models/lotrate.rb
class Lotrate < ActiveRecord::Base
end

walker_server/app/models/qrevent.rb
class Qrevent < ActiveRecord::Base
end

walker_server/app/models/qrlog.rb
class Qrlog < ActiveRecord::Base
end

walker_server/app/models/step.rb
class Step < ActiveRecord::Base
end

walker_server/app/models/step_user.rb
class StepUser < ActiveRecord::Base
end

walker_server/app/models/steplog.rb
class Steplog < ActiveRecord::Base
end

walker_server/app/models/user.rb
class User < ActiveRecord::Base
end

walker_server/app/controllers/gpslogs_controller.rb
class GpslogsController < ApplicationController
  before_action :set_gpslog, only: [:show, :edit, :update, :destroy]

  # GET /gpslogs
  # GET /gpslogs.json
  def index
    @gpslogs = Gpslog.all
  end

  # GET /gpslogs/1
  # GET /gpslogs/1.json
  def show
  end

  # GET /gpslogs/new
  def new
    @gpslog = Gpslog.new
  end

  # GET /gpslogs/1/edit
  def edit
  end

  # POST /gpslogs
  # POST /gpslogs.json
  def create
    @gpslog = Gpslog.new(gpslog_params)

    respond_to do |format|
      if @gpslog.save
        format.html { redirect_to @gpslog, notice: 'Gpslog was successfully created.' }
        format.json { render :show, status: :created, location: @gpslog }
      else
        format.html { render :new }
        format.json { render json: @gpslog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gpslogs/1
  # PATCH/PUT /gpslogs/1.json
  def update
    respond_to do |format|
      if @gpslog.update(gpslog_params)
        format.html { redirect_to @gpslog, notice: 'Gpslog was successfully updated.' }
        format.json { render :show, status: :ok, location: @gpslog }
      else
        format.html { render :edit }
        format.json { render json: @gpslog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gpslogs/1
  # DELETE /gpslogs/1.json
  def destroy
    @gpslog.destroy
    respond_to do |format|
      format.html { redirect_to gpslogs_url, notice: 'Gpslog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gpslog
      @gpslog = Gpslog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gpslog_params
      params.require(:gpslog).permit(:userhash, :longitude, :latitude)
    end
end

walker_server/app/helpers/api_helper.rb
module ApiHelper
end

walker_server/app/helpers/game_api_helper.rb
module GameApiHelper
end

walker_server/app/helpers/gpslogs_helper.rb
module GpslogsHelper
end

walker_server/app/helpers/gpsquests_helper.rb
module GpsquestsHelper
end

walker_server/app/helpers/items_helper.rb
module ItemsHelper
end

walker_server/app/helpers/qrevents_helper.rb
module QreventsHelper
end

walker_server/app/helpers/qrlogs_helper.rb
module QrlogsHelper
end

walker_server/app/helpers/sensor_api_helper.rb
module SensorApiHelper
end

walker_server/app/helpers/steplogs_helper.rb
module SteplogsHelper
end

walker_server/app/helpers/users_helper.rb
module UsersHelper
end

walker_server/app/views/gpslogs/_form.html.haml
= form_for @gpslog do |f|
  - if @gpslog.errors.any?
    #error_explanation
      %h2= "#{pluralize(@gpslog.errors.count, "error")} prohibited this gpslog from being saved:"
      %ul
        - @gpslog.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :userhash
    = f.text_field :userhash
  .field
    = f.label :longitude
    = f.text_field :longitude
  .field
    = f.label :latitude
    = f.text_field :latitude
  .actions
    = f.submit 'Save'

walker_server/app/views/gpslogs/edit.html.haml
%h1 Editing gpslog

= render 'form'

= link_to 'Show', @gpslog
\|
= link_to 'Back', gpslogs_path

walker_server/app/views/gpslogs/index.html.haml
%h1 Listing gpslogs

%table
  %thead
    %tr
      %th Userhash
      %th Longitude
      %th Latitude
      %th
      %th
      %th
      
  %tbody
    - @gpslogs.each do |gpslog|
      %tr
        %td= gpslog.userhash
        %td= gpslog.longitude
        %td= gpslog.latitude
        %td= link_to 'Show', gpslog
        %td= link_to 'Edit', edit_gpslog_path(gpslog)
        %td= link_to 'Destroy', gpslog, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Gpslog', new_gpslog_path

walker_server/app/views/gpslogs/new.html.haml
%h1 New gpslog

= render 'form'

= link_to 'Back', gpslogs_path

walker_server/app/views/gpslogs/show.html.haml
%p#notice= notice

%p
  %b Userhash:
  = @gpslog.userhash
%p
  %b Longitude:
  = @gpslog.longitude
%p
  %b Latitude:
  = @gpslog.latitude

= link_to 'Edit', edit_gpslog_path(@gpslog)
\|
= link_to 'Back', gpslogs_path